@ECHO OFF
IF NOT EXIST ACCOUNTS.F GOTO ERROR
IF NOT EXIST TERMINAL.DLL GOTO ERROR
TITLE Robco Termlink - Terminal Emulator
CLS
ECHO WELCOME TO ROBCO INDUSTRIES (TM) TERMLINK
ECHO.
:BEGIN
SET /P CHOICE=">
IF "%CHOICE%"=="SET TERMINAL/INQUIRE" GOTO VER
IF "%CHOICE%"=="SET FILE/PROTECTION=OWNER:RWED ACCOUNTS.F" GOTO PROTECTION
IF "%CHOICE%"=="SET HALT RESTART/MAINT" GOTO MAINT
IF "%CHOICE%"=="RUN DEBUG/ACCOUNTS.F" GOTO DEBUG
IF "%CHOICE%"=="RUN SHUTDOWN/SYS" GOTO SHUTDOWN
IF NOT "%CHOICE%"== GOTO ERRF
:VER
ECHO.
ECHO RIT-V300
ECHO.
GOTO BEGIN
:PROTECTION
GOTO BEGIN
:MAINT
ECHO.
ECHO Initializing Robco Industries(TM) MF Boot Agent 2.3.0
ECHO RETROS BIOS
ECHO RBIOS-4.02.08.00 52EE5.E7.E8
ECHO Copyright 2201-2203 Robco Ind.
ECHO Uppermem: 64 KB
ECHO Root (5AB)
ECHO Maintenance Mode
ECHO.
GOTO BEGIN
:DEBUG
CLS
TITLE Restricted - You do not have access to this command
ECHO.
ECHO Access restricted.
ECHO Please contact your administrator for more information.
PAUSE >Nul
EXIT
:ERRF
ECHO.
ECHO Invalid Syntax
ECHO.
GOTO BEGIN
:ERROR
EXIT
